"""Feature pipeline orchestrator — builds the complete feature matrix.

Run via ``scripts/02_build_features.py``.  Each row in the output represents
one competitive international match from 2000 onwards.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from loguru import logger
from tqdm import tqdm

from config.settings import settings
from src.features.context_features import compute_context_features, compute_wc_experience
from src.features.elo_features import compute_elo_features
from src.features.form_features import compute_form_features
from src.features.h2h_features import compute_h2h_features
from src.features.ranking_features import compute_ranking_features
from src.features.squad_features import compute_squad_features
from src.features.tactical_features import compute_tactical_features

# ---------------------------------------------------------------------------
# Definitive feature lists — generated by scripts/03_analyse_features.py
# ---------------------------------------------------------------------------

# All features with usable signal (>= 1 non-NaN row).
# XGBoost, LightGBM, RF, Neural Network — handle NaN natively.
FEATURE_COLS_TREES: list[str] = [
    "elo_a",
    "elo_b",
    "elo_diff",
    "elo_trajectory_diff",
    "fifa_pts_diff",
    "squad_log_value_diff",
    "market_value_ratio",
    "ppg_diff",
    "goals_scored_diff",
    "goals_conceded_diff",
    "clean_sheet_diff",
    "win_pct_diff",
    "neutral_win_pct_diff",
    "h2h_win_rate",
    "h2h_goal_diff_avg",
    "h2h_neutral_win_rate",
    "h2h_n_matches",
    "wc_appearances_diff",
    "avg_wc_finish_diff",
    "rest_days_diff",
    "round_importance"
]

# Reduced set for logistic regression — multicollinear and redundant features
# removed based on Pearson |r| > 0.85 and iterative VIF pruning (threshold 10).
# NaN values in this set are median-imputed at train time.
FEATURE_COLS_LINEAR: list[str] = [
    "elo_diff",
    "elo_trajectory_diff",
    "fifa_pts_diff",
    "squad_log_value_diff",
    "ppg_diff",
    "goals_scored_diff",
    "goals_conceded_diff",
    "clean_sheet_diff",
    "neutral_win_pct_diff",
    "h2h_goal_diff_avg",
    "h2h_neutral_win_rate",
    "h2h_n_matches",
    "wc_appearances_diff",
    "rest_days_diff",
    "round_importance"
]

# Backwards-compatible alias imported by existing pipeline / Phase 3 code.
FEATURE_COLS = FEATURE_COLS_TREES



def _build_team_elo_index(elo_df: pd.DataFrame) -> dict[str, pd.DataFrame]:
    """Pre-index Elo data by team for O(1) per-team lookups."""
    idx: dict[str, pd.DataFrame] = {}
    for team, grp in elo_df.groupby("team"):
        idx[str(team)] = grp.sort_values("date").reset_index(drop=True)
    return idx


def _build_team_matches_index(matches_df: pd.DataFrame) -> dict[str, pd.DataFrame]:
    """Pre-index match history by team for faster form / H2H lookups."""
    idx: dict[str, pd.DataFrame] = {}
    all_teams = set(matches_df["home_team"].unique()) | set(matches_df["away_team"].unique())
    for team in all_teams:
        team_matches = matches_df[
            (matches_df["home_team"] == team) | (matches_df["away_team"] == team)
        ].copy()
        idx[team] = team_matches.sort_values("date").reset_index(drop=True)
    return idx


def build_feature_matrix(
    matches_df: pd.DataFrame,
    elo_df: pd.DataFrame,
    rankings_df: pd.DataFrame,
    squad_df: pd.DataFrame,
    fbref_shooting_df: pd.DataFrame,
    fbref_keeper_df: pd.DataFrame,
    start_year: int = 2000,
) -> pd.DataFrame:
    """Build the complete feature matrix from source DataFrames.

    Each row corresponds to one competitive international match.
    All features are computed with a strict ``date < cut_date`` filter
    to prevent any form of data leakage.

    Args:
        matches_df:        Cleaned match history (``matches_clean.parquet``).
        elo_df:            Cleaned Elo history (``elo_clean.parquet``).
        rankings_df:       Cleaned FIFA rankings (``rankings_clean.parquet``).
        squad_df:          Transfermarkt squad values (``squad_values.parquet``).
        fbref_shooting_df: FBref shooting data (loaded by ``tactical_features``).
        fbref_keeper_df:   FBref keeper data (loaded by ``tactical_features``).
        start_year:        Earliest match year to include (default 2000).
                           Matches before this year still serve as historical context.

    Returns:
        DataFrame with META_COLS + TARGET_COLS + FEATURE_COLS columns, also saved to
        ``data/processed/feature_matrix.parquet``.
    """
    logger.info("Building feature matrix...")

    # --- Filter to competitive matches from start_year onwards ---
    df = matches_df[
        (matches_df["is_competitive"])
        & (matches_df["date"].dt.year >= start_year)
    ].copy()
    df = df.dropna(subset=["home_score", "away_score"])
    df = df.sort_values("date").reset_index(drop=True)
    logger.info(f"Processing {len(df):,} competitive matches from {start_year} onwards")

    # --- Compute targets ---
    df["outcome"] = np.where(
        df["home_score"] > df["away_score"], 2,
        np.where(df["home_score"] == df["away_score"], 1, 0),
    )

    # --- Pre-build indexes for speed ---
    logger.info("Pre-building team indexes for faster lookups...")
    team_matches_idx = _build_team_matches_index(matches_df)

    rows: list[dict] = []
    errors = 0

    for _, row in tqdm(df.iterrows(), total=len(df), desc="Building features"):
        cut_date = pd.Timestamp(row["date"])
        team_a = str(row["home_team"])
        team_b = str(row["away_team"])

        try:
            # ---- Elo features ----
            elo_feats = compute_elo_features(row, elo_df)

            # ---- FIFA ranking features ----
            rank_feats = compute_ranking_features(row, rankings_df)

            # ---- Recent form (using per-team match index) ----
            form_a = compute_form_features(matches_df, team_a, cut_date, n=10)
            form_b = compute_form_features(matches_df, team_b, cut_date, n=10)

            def _form_diff(key_a: str, key_b: str) -> float:
                va, vb = form_a[key_a], form_b[key_b]
                if np.isnan(va) or np.isnan(vb):
                    return np.nan
                return float(va - vb)

            # ---- H2H features ----
            h2h_feats = compute_h2h_features(matches_df, team_a, team_b, cut_date)

            # ---- Squad features ----
            squad_feats = compute_squad_features(squad_df, team_a, team_b)

            # ---- Context features ----
            ctx_feats = compute_context_features(row)

            # ---- WC experience ----
            wc_feats = compute_wc_experience(matches_df, team_a, team_b, cut_date)

            # ---- Tactical features (FBref) ----
            tact_feats = compute_tactical_features(
                fbref_shooting_df, fbref_keeper_df, team_a, team_b, cut_date
            )

            feature_row: dict = {
                # Meta
                "match_date":  row["date"],
                "team_a":      team_a,
                "team_b":      team_b,
                "tournament":  str(row.get("tournament", "")),
                "is_neutral":  int(bool(row.get("neutral", True))),
                # Targets
                "outcome":     int(row["outcome"]),
                "goals_a":     int(row["home_score"]),
                "goals_b":     int(row["away_score"]),
                # Elo
                "elo_a":               elo_feats["elo_a"],
                "elo_b":               elo_feats["elo_b"],
                "elo_diff":            elo_feats["elo_diff"],
                "elo_trajectory_diff": elo_feats["elo_trajectory_diff"],
                # FIFA ranking
                "fifa_pts_diff": rank_feats["fifa_pts_diff"],
                # Squad value
                "squad_log_value_diff": squad_feats["squad_log_value_diff"],
                "market_value_ratio":   squad_feats["market_value_ratio"],
                # Form diffs
                "ppg_diff":            _form_diff("ppg", "ppg"),
                "goals_scored_diff":   _form_diff("goals_scored_pg", "goals_scored_pg"),
                "goals_conceded_diff": _form_diff("goals_conceded_pg", "goals_conceded_pg"),
                "clean_sheet_diff":    _form_diff("clean_sheet_pct", "clean_sheet_pct"),
                "win_pct_diff":        _form_diff("win_pct", "win_pct"),
                "neutral_win_pct_diff":_form_diff("neutral_win_pct", "neutral_win_pct"),
                # H2H
                "h2h_win_rate":         h2h_feats["h2h_win_rate"],
                "h2h_goal_diff_avg":    h2h_feats["h2h_goal_diff_avg"],
                "h2h_neutral_win_rate": h2h_feats["h2h_neutral_win_rate"],
                "h2h_n_matches":        h2h_feats["h2h_n_matches"],
                # WC experience
                "wc_appearances_diff": wc_feats["wc_appearances_diff"],
                "avg_wc_finish_diff":   wc_feats["avg_wc_finish_diff"],
                # Context
                "rest_days_diff":  ctx_feats["rest_days_diff"],
                "round_importance": ctx_feats["round_importance"],
                # Tactical
                "xg_diff_per_game": tact_feats["xg_diff_per_game"],
                "sot_pct_diff":     tact_feats["sot_pct_diff"],
            }
            rows.append(feature_row)

        except Exception as exc:
            errors += 1
            logger.warning(f"Error on {team_a} vs {team_b} ({row['date'].date()}): {exc}")
            continue

    if errors:
        logger.warning(f"Skipped {errors} matches due to errors")

    fm = pd.DataFrame(rows)

    # --- Enforce column order ---
    ordered_cols = META_COLS + TARGET_COLS + FEATURE_COLS
    for col in ordered_cols:
        if col not in fm.columns:
            fm[col] = np.nan
    fm = fm[ordered_cols]

    # --- Save ---
    out_path = settings.DATA_DIR / "processed" / "feature_matrix.parquet"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fm.to_parquet(out_path, engine="pyarrow", index=False)

    # --- Summary ---
    logger.info(f"\nFeature matrix: {len(fm):,} rows × {len(fm.columns)} columns")
    logger.info(f"Date range: {fm['match_date'].min().date()} → {fm['match_date'].max().date()}")
    outcome_dist = fm["outcome"].value_counts(normalize=True).sort_index()
    logger.info(f"Outcome distribution (0=B wins, 1=draw, 2=A wins): {outcome_dist.to_dict()}")

    nan_counts = fm[FEATURE_COLS].isnull().sum()
    if nan_counts.any():
        logger.info(f"NaN counts per feature:\n{nan_counts[nan_counts > 0].to_string()}")

    return fm


def load_feature_matrix(path: str | Path | None = None) -> tuple[pd.DataFrame, list[str]]:
    """Load the saved feature matrix from disk.

    Args:
        path: Path to the parquet file. Defaults to ``data/processed/feature_matrix.parquet``.

    Returns:
        Tuple of ``(feature_matrix_df, FEATURE_COLS)`` for use by training scripts.
    """
    if path is None:
        path = settings.DATA_DIR / "processed" / "feature_matrix.parquet"
    fm = pd.read_parquet(path)
    return fm, FEATURE_COLS
